version: '3.8'

services:
  mindswap-mariadb:
    image: mariadb:latest
    container_name: reviewer-mariadb
    ports:
      - '3306:3306'
 #   volumes:
 #     - './data/mariadb:/var/lib/mysql'
    environment:
      MARIADB_ROOT_PASSWORD: 'mypass'
      MARIADB_DATABASE: 'mindswap'
    restart: always
 #   networks:
 #     - mindswap-net
#    depends_on:
#      - mindswap-redis
#    logging:
#      driver: syslog
#      options:
#        syslog-address: tcp://
  mindswap-app:
    image : reviewer-image
    restart: on-failure
    container_name: reviewer-app
    depends_on:
      - reviewer-mariadb
    ports:
      - '8080:8080'
    environment:
      MARIADB_DB: 'mindswap'
      MARIADB_USER: 'group1'
      MARIADB_PASSWORD: 'Group1Password!'
      MARIADB_URL: jdbc:mariadb://ms-2nd-edition-groups-db00006104.mdb0002418.db.skysql.net:5003/group1?useSSL=true&trustServerCertificate=true
      SERVER_PORT: '8080'
      HIBERNATE_DDL_AUTO: 'update'
